// This file is auto-generated by Supabase CLI
// Run `npm run db:generate-types` to update

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      intercom_actions: {
        Row: {
          id: string
          user_id: string
          action: 'buzz' | 'status_check'
          status: 'pending' | 'success' | 'failed'
          created_at: string
          completed_at: string | null
          error_message: string | null
        }
        Insert: {
          id?: string
          user_id: string
          action: 'buzz' | 'status_check'
          status: 'pending' | 'success' | 'failed'
          created_at?: string
          completed_at?: string | null
          error_message?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          action?: 'buzz' | 'status_check'
          status?: 'pending' | 'success' | 'failed'
          created_at?: string
          completed_at?: string | null
          error_message?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "intercom_actions_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      intercom_status: {
        Row: {
          id: string
          is_online: boolean
          last_buzz: string | null
          battery_level: number | null
          signal_strength: number | null
          updated_at: string
        }
        Insert: {
          id?: string
          is_online?: boolean
          last_buzz?: string | null
          battery_level?: number | null
          signal_strength?: number | null
          updated_at?: string
        }
        Update: {
          id?: string
          is_online?: boolean
          last_buzz?: string | null
          battery_level?: number | null
          signal_strength?: number | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
